roles = [
				["Rifleman","Rifleman.sqf"],
				["Grenadier","Grenadier.sqf"],
				["MG","MG.sqf"],
				["MG-Assistant","MG-Assistant.sqf"],
				["Autorifle","autorifle.sqf"],
				["AT","AT.sqf"],
				["AT-Assistant","AT-Assistant.sqf"],
				["AA","AA.sqf"],
				["AA-Assistant","AA-Assistant.sqf"],
				["AT-Light","AT-Light.sqf"],
				["DM","DM.sqf"],
				["EOD","EOD.sqf"],
				["Engineer","Engineer.sqf"],
				["JTAC","JTAC.sqf"],
				["Medic","Medic.sqf"],
				["Squadleader","Squadleader.sqf"],
				["Groupleader","Groupleader.sqf"],
				["Sniper","Sniper.sqf"],
				["Spotter","Spotter.sqf"],
				["Diver-Groupleader","Diver-Groupleader.sqf"],
				["Diver-EOD","Diver-EOD.sqf"],
				["Diver-Medic","Diver-Medic.sqf"],
				["Diver-Rifleman","Diver-Rifleman.sqf"],
				["Pilot","Pilot.sqf"],
				["Fighter-Pilot","Fighter-Pilot.sqf"],
				["AV Crew","crew.sqf"]
];
publicVariable "roles";